version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipassword
      POSTGRES_DB: incidentes_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      FLASK_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

volumes:
  db_data:
